services:
  app:
    # image: ghcr.io/ohsucmp/coach
    image: p3000/coach:latest
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - cqfruler
    volumes:
      - ./docker_data/coach/logs:/opt/app/logs
      # to override logging configuration, mount a logback.xml file to /opt/app/config
      # - ./docker_data/coach/logback.xml:/opt/app/config/logback.xml
      # to override configuration properties, mount an application.properties file to /opt/app/config
      - ./docker_data/coach/application.properties:/opt/app/config/application.properties
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://coach:coach@mysql/coach
      - CQFRULER_CDSHOOKS_ENDPOINT_URL=http://cqfruler:8080/cds-services
    command: wait-for-it mysql:3306 -s -t 10 -- java -Dlogging.config=/opt/app/config/logback.xml -jar /opt/app/coach.jar
  mysql:
    image: mysql:8
    volumes:
      - ./docker_data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=coach
      - MYSQL_USER=coach
      - MYSQL_PASSWORD=coach
      - MYSQL_ROOT_PASSWORD=root
  cqfruler:
    image: alphora/cqf-ruler:0.13.0
    ports:
      - "8080:8080"
    volumes:
      - ./docker_data/cqfruler:/data
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/h2
