# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: get latest release with tag
      id: latestrelease
      run: |
          echo "::set-output name=releasetag::$(curl -s https://api.github.com/repos/OHSUCMP/coach/releases/latest | jq '.tag_name' | sed 's/\"//g')"
    - name: confirm release tag
      run: |
          echo ${{ steps.latestrelease.outputs.releasetag }}
    - name: tagcheckout
      uses: actions/checkout@v4
      with:
          ref: ${{ steps.latestrelease.outputs.releasetag }}
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '17'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

    - name: Build with Maven
      run: mvn package -DskipTests

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -DskipTests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
